puts "The Students of Cartoons Academy"
puts "---------"
puts "Twilight Sparkle"
puts "Rainbow Dash"
puts "Pinkie Pie"
puts "Pearl"
puts "Steven Universe"
puts "Kony"
puts "Marco"
puts "Star Butterfly"
puts "Ami Mizuno"
puts "Princess Bubblegum"
puts "Marceline The Vampire Queen"
puts "Dexter"